services: 
  nginx:
    image: nginx:1.25.5
    ports: 
      - "80:80"
    volumes:
      - "./apigw/nginx.conf:/etc/nginx/nginx.conf"
    depends_on: 
      - swagger-ui
      - sudoku-site
    
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.5
    volumes:
      - "./docs/documentation.yaml:/documentation.yaml"
    environment:
      SWAGGER_JSON: /documentation.yaml
      BASE_URL: /swagger

  sudoku-site:
    image: sudoku-site:latest
    build: ./sudoku_site
