services: 
  nginx:
    image: nginx:1.25.5
    ports: 
      - "80:80"
    volumes:
      - "./apigw/nginx.conf:/etc/nginx/nginx.conf"
    depends_on: 
      - swagger-ui
      - backend
    
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.5
    volumes:
      - "./docs/documentation.yaml:/documentation.yaml"
    environment:
      SWAGGER_JSON: /documentation.yaml
      BASE_URL: /swagger

  backend:
    image: backend:latest
    build: ./backend
