services: 
  apigw:
    image: nginx:1.25.5
    ports: 
      - "80:80"
    volumes:
      - "./apigw/nginx.conf:/etc/nginx/nginx.conf"
    depends_on: 
      - docs
      - webapp
    
  docs:
    image: swaggerapi/swagger-ui:v5.17.5
    volumes:
      - "./docs/documentation.yaml:/documentation.yaml"
    environment:
      SWAGGER_JSON: /documentation.yaml
      BASE_URL: /swagger

  webapp:
    image: webapp:latest
    build: ./webapp
